### PR TITLE
Minor change to Readme

### PR DESCRIPTION
**Pull request by Achilles-96**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Please make it a single commit.

It is still slightly confusing. Becoming root should not be required apart from when installing gulp globally. If we run other commands as root too, it might cause some problems.

**Comment by Achilles-96** [comment]
npm also required me to become root.

**Comment by nisargjhaveri** [comment]
You're talking about `npm install -g gulp`, right?

**Comment by Achilles-96** [comment]
No, I'm talking about npm install. Also, it didn't create any problems running as root

**Comment by nisargjhaveri** [comment]
Okay!

Squash the commits, though.

**Comment by nisargjhaveri** [comment]
Merged.

Thanks :)

**Comment by hharchani** [comment]
But why is npm install asking for root?

**Comment by nisargjhaveri** [comment]
I don't know.. @Achilles-96?

**Comment by Achilles-96** [comment]
May be because of repo's location(/var/www/html) or may be due to global proxy setting for npm.

**Comment by polybuildr** [comment]
It's either because of the location `/var/www/html` or because of a global install. However, I'm not convinced we should be changing the README for this because it's a local environment issue.

If the location of the repo locally is the issue, either soft link it or run the command as root at your own risk.

If it's a global install, either use nvm or n -  which won't require root, as I think I mentioned in the README, or run as root at your own risk.

Should we really be giving explicit instructions to run these as root, especially when the packages we use could run arbitrary code on install?

**Comment by Achilles-96** [comment]
That is the reason I said 'if necessary', so that if someone faces this problem, they will have a clue.

**Comment by polybuildr** [comment]
@Achilles-96 the thing is, we should be saying that the setup should be such that they shouldn't require root. If someone faces this problem, the clue we should give them is that their setup probably should change a bit.

But I'm probably making this too big of an issue. For pragmatic reasons, running the command as `sudo` makes perfect sense. Let's go with it. :+1:

**Pull request merged**
