### PR TITLE
Make desc in create mission required

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Wow! hub actually works! :P

**Comment by polybuildr** [comment]
Why make it required? I was looking at the missions and for example, 'Create social networking accounts` missions can have tasks 'Create a Twitter account and give the link here', 'Create a LinkedIn account and give the link here' and no description is required for the mission itself.

P. S. Of course `hub` works. :P

**Comment by nisargjhaveri** [comment]
Gadhe. Because it is required in controller. And when you submit without it, it just removes text from all other fields and gives a nice error! :P

**Comment by polybuildr** [comment]
Oops. It should really not be required in the controller. -_- I'll merge this and then submit one for that. Sorry! :P

**Comment by nisargjhaveri** [comment]
Okay! :P

**Comment by polybuildr** [comment]
Submitted #78.

**Pull request merged**
