### PR TITLE
Create database if it doesn't exist

### PR DESCRIPTION
**Pull request by erilyth**

### CODE REVIEW

**Comment by polybuildr** [comment]
This will mean that nobody can use their own name for the database, which could be necessary in some setups (access only to `test` database). Any suggestions?

Also, you should probably fix your system time, unless you actually committed 6 hours back. :P

**Comment by polybuildr** [comment]
The other change is a good idea, though - clearer instructions are always awesome.

If you think that the database should not be automatically created, please certainly open another PR with better instructions.

You can also specify a db to import into using the command line:
`mysql -u username -ppassword DBNAME < filename.sql`

**Comment by erilyth** [comment]
Yea I think you are right, maybe including that in the readme for now would be good.

**Comment by polybuildr** [comment]
:+1:

**Comment by polybuildr** [comment]
Since this is unrelated to the previous issue, fluid you please open a new PR?

**Pull request closed without merging**
