### PR TITLE
External data support in Jugaad

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Will resolve T97.

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
For now, just the path expansion logic is there. But some reviews and tests for that would really help.

Also, `get_directory` method, which is used at many places is also changed. So, testing for that too would help.

### How to test?

Add something like 

```
var_dump($this->jugaad_model->expand_regex_paths('**/.*', "d.*"));
exit();
```

to `jugaad::read` and open any page in Jugaad.

I've kept those methods public for now, so that it is easier to test.

**Comment by nisargjhaveri** [comment]
Added the remaining part for external data. Still not merge-able, but works with templates.

**Comment by nisargjhaveri** [comment]
User permissions are now being checked.

**Comment by nisargjhaveri** [comment]
Added one more commit.

The last commit has a lot of debug stuff. That is intentional. I really need some reviews at this point.

Someone, please please please test?

**Comment by nisargjhaveri** [comment]
Known bug: When using `**` at the end, it does not look at `template`.

Will fix that.

**Comment by Achilles-96** [comment]
`**` is supposed to be replaced with any prefix.
So `**/some.*` should give any files with some as prefix located at any depth. But it external data is empty.

**Comment by nisargjhaveri** [comment]
Seems to be working for me. Can you provide some more info?

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by nisargjhaveri** [comment]
Rebased. Updated.

**Comment by polybuildr** [comment]
Too large to review thoroughly. Glanced through, looks okay. Tested sort-of. :P

What could go wrong?...

**Pull request merged**
