### PR TITLE
Implement Jugaad API

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Resolves T179.

### CODE REVIEW

**Comment by polybuildr** [comment]
{Resolves T179}.

**Comment by hharchani** [comment]
Kya karta hai be. Merge conflict solve kar. :/

**Comment by hharchani** [comment]
@nisargjhaveri

**Comment by nisargjhaveri** [comment]
Updated

**Comment by hharchani** [comment]
When sending json, set ContentType header to json.

**Comment by hharchani** [comment]
Looks fine. Tested and working.

**Pull request merged**
