### PR TITLE
Add flash_append method to session_lib

### PR DESCRIPTION
**Pull request by polybuildr**
This lets you append to an array in the flash data, creating one first
if it does not exist. This is particularly useful in cases such as
errors, `$this->session_lib->flash_append('errors', 'foo bar');` lets you
append errors from anywhere in the code without worrying about whether
the 'errors' array exists in the flash data.

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Nope. I don't think this is a job of sessions lib.

I think we should handle the array and at the end set the flash data. And handling array of errors should be equivalently easy with something like `$errors[] = "foo bar";`. And at the end setting the flash data.

**Comment by polybuildr** [comment]
@nisargjhaveri unfortunately, that's not possible in the case I'm talking about.`$errors` might not even be in scope when you're setting it, it could be happening in different methods in a controller, or even in a library. We'd have to pass around `$errors` all the time.

Additionally, we have to check if it exists, if it doesn't, we have to `= []`. Then we can append.

There are a lot of issues. This method would make things much simpler.

**Comment by hharchani** [comment]
I agree with @nisargjhaveri

**Comment by polybuildr** [comment]
@hharchani, how do you propose we handle those cases then?

**Comment by hharchani** [comment]
We can get from session, change and set it again.

**Comment by nisargjhaveri** [comment]
That also works.

But to put it slightly differently, we basically are making random global variables. You need a global variable for errors in your case. And in general use of such global variables are discouraged. So, something wrong with the design. And trust me, setting errors in this fashion creates lots of problems.

**Comment by polybuildr** [comment]
@hharchani, the problem with that is the extra code.

``` php
$errors = $this->session_lib->flash_get('errors');
if (!$errors) {
    $errors = [];
}
$errors[] = "Please don't spam us.";
$errors = $this->session_lib->flash_set('errors', $errors);
```

vs.

``` php
$this->session_lib->flash_append('errors', "Please don't spam us.");
```

@nisargjhaveri that is true. Alright then, I'll close this until a case comes up. And we'll discuss it when it does.

**Comment by hharchani** [comment]
also, $errors = $this->session_lib->flash_get('errors') ? : [];

**Comment by polybuildr** [comment]
Point. :P Also, that needs to be done in a few places in the code too.

**Comment by nisargjhaveri** [comment]
No doubt it is easier. But don't think if we should have it.

Let's wait and see.

**Pull request closed without merging**
