### PR TITLE
Fixed refine ui templates

### PR DESCRIPTION
**Pull request by hharchani**

### CODE REVIEW

**Comment by polybuildr** [comment]
I think you should include some pages as part of the SQL.

**Comment by polybuildr** [comment]
The "felicity" transition is deterministically buggy on Chrome.

**Comment by polybuildr** [comment]
The glowing orb is also noticeably buggy on Chrome.

**Comment by polybuildr** [comment]
The glowing orb, though, doesn't seem to be deterministic - sometimes buggy, sometimes not. I have no idea what causes it to go from one to the other though.

Also, we're back to ~100% CPU usage on Chrome, which is new.

**Comment by polybuildr** [comment]
Let's take the risk. :P

**Comment by ParthKolekar** [comment]
+1

My +1 counts too right?

**Comment by nisargjhaveri** [comment]
@ParthKolekar, in this case, no. :P

**Comment by ParthKolekar** [comment]
@nisargjhaveri  
:P 

k

**Pull request merged**
