### PR TITLE
Add lists and datetime in Jugaad

### PR DESCRIPTION
**Pull request by nisargjhaveri**
resolves T99

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by nisargjhaveri** [comment]
Sorry, I had to build upon this PR, so added date/time also in the same PR.
{resolves T100}

**Comment by hharchani** [comment]
Does this branch needs rebase?

**Comment by polybuildr** [comment]
> This branch has no conflicts with the base branch

Probably not.

**Comment by hharchani** [comment]
When I pull, it adds a merge commit.

**Comment by polybuildr** [comment]
Oh. Point. "merging can be performed automatically" does not mean that it will only be a fast-forward. Let me check too.

**Comment by nisargjhaveri** [comment]
Even if it cannot be fast-forwarded, we don't need a rebase here, I think.

**Comment by polybuildr** [comment]
Okay, probably does need a rebase. /cc @nisargjhaveri

**Comment by polybuildr** [comment]
> Even if it cannot be fast-forwarded, we don't need a rebase here, I think.

Why not?

**Comment by nisargjhaveri** [comment]
Why?

**Comment by polybuildr** [comment]
xP

**Comment by hharchani** [comment]
Lists are nice.

**Comment by hharchani** [comment]
@nisargjhaveri can't this be done that empty list are actually empty array and not empty string? please? :P

**Comment by hharchani** [comment]
if your answer is still no, we can merge this. I've tested, it works :smiley:

**Comment by nisargjhaveri** [comment]
Answer is still no for now. :P

**Comment by polybuildr** [comment]
Good morning, Harshit! :P

Vivek Ghaisas

**Pull request merged**
