### PR TITLE
Fixed Vivek's bug

### PR DESCRIPTION
**Pull request by ParthKolekar**
Vivek!!!

### CODE REVIEW

**Comment by ParthKolekar** [comment]
@polybuildr 

Vivek!!

**Comment by polybuildr** [comment]
wut. Mine works, you're breaking HTML. Kehna kya chahta hai? :P

**Comment by ParthKolekar** [comment]
@polybuildr 

Vivek!!

:stuck_out_tongue:

**Comment by polybuildr** [comment]
Oops.

**Pull request merged**
