### PR TITLE
Add normalize.css v3.0.2

### PR DESCRIPTION
**Pull request by polybuildr**
Supports: Chrome, Firefox, Opera, Safari 6+, IE 8+

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Why is this not minified?

**Comment by polybuildr** [comment]
It's not minified so that we can make any changes if we want to. In addition, the build process can minify it when we write a production task for gulp.

Do you think it should be minified anyway?

**Comment by nisargjhaveri** [comment]
We should not make any changes to third party libraries, residing in vendor! Yes, I think it should be minified.

**Comment by polybuildr** [comment]
Updated PR:
- Minified using clean-css

**Comment by nisargjhaveri** [comment]
Oops! They don't provide a minified version!? Then I'm not so sure about minifing it. (same thing, don't mess with vendor libraries)

But still I think, it should be minified! :P Now, up to you.

If we keep the minified version, a couple of suggestions,
- keep the first comment and rest of the file in separate lines
- A new line at the end of file?

**Comment by polybuildr** [comment]
- Regarding minification at all: https://github.com/necolas/normalize.css/commit/2bc78e7272599148a03da4e357475d2a56f51822
- Regarding license comment and ending newline: Why? Sure, it looks good and all, and `cat` etc. play well with ending newlines but it's a minified library, surely that doesn't matter?

**Comment by nisargjhaveri** [comment]
No, it doesn't matter much, I just compared it with minified jQuery! :P

And looks like people does it the same way, so looks fine!

**Comment by nisargjhaveri** [comment]
Should we merge this?

**Comment by polybuildr** [comment]
I think it's a good idea to minify this as part of the build process, but
let's do that later, if at all.

:+1:

**Pull request merged**
