### PR TITLE
[WIP] Add user registration logic for OAuth users

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
TODO
- [ ] A lots and lots of input validation
- [x] Password reset link
- [ ] Testing
- [ ] Styling
- [ ] ...

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by meghprkh** [comment]
Can you pls merge my PR

**Comment by nisargjhaveri** [comment]
Yes, on it.

**Pull request merged**
