### PR TITLE
Update GA to include ELA

### PR DESCRIPTION
**Pull request by ParthKolekar**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
> "For the most accurate link attribution, each of the links on your page should have a unique element ID."

I don't think we have them.

**Comment by ParthKolekar** [comment]
Don't need it.

**Comment by ParthKolekar** [comment]
@polybuildr 
@nisargjhaveri 
@hharchani 

require +2

**Comment by hharchani** [comment]
Abey, 'linkid' should be link's unique id, otherwise what's the point?

**Comment by ParthKolekar** [comment]
Recommended. Not required.

**Comment by hharchani** [comment]
I don't see any point of it, seareiously

**Pull request closed without merging**
