### PR TITLE
Add task to copy vendor/ into build/

### PR DESCRIPTION
**Pull request by polybuildr**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Hidden files are not getting copied.

**Comment by polybuildr** [comment]
Updated PR.
- Hidden files now copied, using `{dot: true}` option.
- Removed `base` option and instead used `build/vendor` in `gulp.dest`

**Comment by polybuildr** [comment]
Ping?
/cc @hharchani

**Comment by polybuildr** [comment]
Self-merging.

**Pull request merged**
