### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by ParthKolekar**

### CODE REVIEW

**Comment by polybuildr** [comment]
I wish you'd write a better commit message. -_- But meh.

**Comment by ParthKolekar** [comment]
What is wrong with the commit message?

**Comment by polybuildr** [comment]
It doesn't give any idea as to what actually changed in the commit. "Also run linting tests on HVVM" or something? :P

**Comment by ParthKolekar** [comment]
Branch name.

**Pull request merged**
