### PR TITLE
Add JSHint configuration in .jshintrc

### PR DESCRIPTION
**Pull request by polybuildr**

### CODE REVIEW

**Comment by polybuildr** [comment]
This depends on #42 and the build will fail without that being merged.

**Comment by polybuildr** [comment]
Updated PR. `unused` is now set to `"vars"`. It will not report unused function parameters.

**Comment by nisargjhaveri** [comment]
Why not function parameters?

**Comment by polybuildr** [comment]
We could also put that in, but there are cases where it's annoying.
For example at http://stackoverflow.com/questions/6583623/jslint-message-unused-variables,

```
$.each(data, function (i, item) {
    // do something with "item"
});
```

This will give an error that `i` is unused. (We could ignore these particular cases with comments though. Would you prefer that, and keep `unused` to `true` - including function parameters?)

**Comment by nisargjhaveri** [comment]
Umm, depends on how many times this case arises. Also doesn't make much difference. You decide.

**Comment by polybuildr** [comment]
Strictness is always preferable unless it gets in the way. Changed it back to report errors about all unused variables. When it gets in the way, we'll consider a change.

Since #42 is now merged, this is mergeable.

**Comment by nisargjhaveri** [comment]
Do we have to write `/*jslint unparam: true/false*/` comments to ignore that? It seems to risky to use.

**Comment by polybuildr** [comment]
Yeah, to ignore that on a case-to-case basis, you need to use those kind of comments. Sorry, but what do you mean by "risky to use"?

**Comment by nisargjhaveri** [comment]
There are high chances of forgetting to set it to false again!

**Comment by polybuildr** [comment]
Okay, I put some more research into this. Firstly, https://github.com/mbulman/jshint/commit/1cca4c2848fb9745fd333819d57b844bb8145d97 fixed the issue I wrote about above. If you use the second parameter, `unused: true` will not complain about the first parameter being unused (though `unused: "strict"` will).

Secondly, this directive (like many others) has a function scope, so if we put `/* jshint unused:vars */` as the first line of the function, this will hide this error for this function and restore it outside function scope, which seems fine, imho.

**Comment by nisargjhaveri** [comment]
Okay, looks good.

**Pull request merged**
