### PR TITLE
Minor updates in README and INSTALL

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by nisargjhaveri** [comment]
Again, updated.

**Comment by nisargjhaveri** [comment]
Also, I feel there is no need of INSTALL.md, we should just link to respective help pages, as it is not actually about installing our system/application, it is just about installing dependencies. And, it'll eventually get outdated. Better to outsource the responsibility.

**Comment by polybuildr** [comment]
I think that makes sense. But let's leave it in for a while to aid new contributors.

LGTM. Merging.

**Pull request merged**
