### PR TITLE
Complete ajaxification of templates

### PR DESCRIPTION
**Pull request by hharchani**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Build failing.

**Comment by hharchani** [comment]
@nisargjhaveri Fixed.

**Comment by nisargjhaveri** [comment]
Some problem in Chrome, talked to @hharchani directly.

**Comment by hharchani** [comment]
@nisargjhaveri test now

**Comment by nisargjhaveri** [comment]
Looks good.

**Pull request merged**
