### PR TITLE
Get Travis to only notify Slack on failing builds

### PR DESCRIPTION
**Pull request by polybuildr**
Not sure if this works, `on_success` doesn't seem to be supported for Slack notifications as per http://docs.travis-ci.com/user/notifications/#Slack-notifications, but it doesn't hurt to try.

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
It didn't work right? It still notified for this PR. Or it force-uses config from `master`?

**Comment by polybuildr** [comment]
AFAICS, this didn't work. (Also commented after the notification in slack itself.)

**Comment by polybuildr** [comment]
travis-ci/travis-ci#2894

The `:change` syntax might work.

**Comment by polybuildr** [comment]
Is it okay if I merge this to test and then revert it later if it fails? /cc @nisargjhaveri @hharchani

**Comment by nisargjhaveri** [comment]
Seems fine.

**Pull request merged**
